name: learn-github-actions
on:
    push:
        branches:
            - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        - name: "Check out code"
            shell: bash
            env:
                SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
            run: |
                npm install -g bats
                bats -v
                echo "$SUPER_SECRET"
