name: learn-github-actions
on:
    push:
        branches:
            - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        - name: "Check out code"
            shell: bash
            env:
                SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
            run: |
                npm install -g bats
                bats -v
                echo "$SECRET_TOKEN"
