name: learn-github-actions
on:
    push:
        branches:
            - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/philippe-neveux/data-sciences:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
        - name: "Check out code"
          shell: bash
          env:
            SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          run: |
            echo "$SECRET_TOKEN"
            poetry
            which python
